project:
  type: website
website:
  title: "RI-CLPM 2024"
  navbar:
    left:
      - href: index.qmd
        text: Home
    right:
    - icon: github
      href: https://github.com/

format:     
  html:
    theme: simplex
    
execute:
  freeze: auto